### ISSUE TITLE
questionable form "liveed" of en:live 

### ISSUE THREAD

**Issue by karlb** [karlb/wikdict-gen#11]
```
sqlite3 processed/en.sqlite3
sqlite> SELECT * FROM form WHERE lexentry LIKE 'eng/live\_\_%' ESCAPE '\' AND other_written_full = 'liveed';
lexentry           other_written_full  pos   rank  number  mood        person  tense  voice   case    definiteness  inflection  other_written
-----------------  ------------------  ----  ----  ------  ----------  ------  -----  ------  ------  ------------  ----------  -------------
eng/live__Verb__1  liveed              verb  4     (null)  Participle  (null)  Past   (null)  (null)  (null)        (null)      liveed
eng/live__Verb__1  liveed              verb  3     (null)  (null)      (null)  Past   (null)  (null)  (null)        (null)      liveed
```
Where does this form come from? I don't see it on https://en.wiktionary.org/wiki/live
Problem visible on https://www.wikdict.com/de-en/live

**Comment by Vuizur** [comment]
I think Tatu Ylonen also wrote about this in his [Wiktextract paper](http://www.lrec-conf.org/proceedings/lrec2022/pdf/2022.lrec-1.140.pdf): It seems like the Dbnary reimplemented the Wiktionary Lua templates for some languages, causing some bugs in the process.

**Comment by karlb** [comment]
Good find. I'll check if the problem still exists in the latest version and file a bug upstream, if it does.

**Comment by karlb** [comment]
The latest dbnary data looks good!
