### ISSUE TITLE
Missing entries from an update to another

### ISSUE THREAD

**Issue by ookiiwi** [karlb/wikdict-gen#15]
Hello, while searching for common words in the eng-jpn dictionary, I found out that the word 'car' is not in the [last version](https://download.wikdict.com/dictionaries/tei/recommended/eng-jpn.tei) of this dictionary while it was in the [previous one](https://download.wikdict.com/dictionaries/tei/recommended/2020-02/eng-jpn.tei).

**Comment by karlb** [comment]
I can confirm the problem. It looks like a bug in the Virtuoso DB that is used in the data pipeline. The data in the DB looks good and the query does too (it works on a different instance), but running the query doesn't return the expected result. I'll try recreating the db from scratch with the latest virtuoso version and report back.

Thanks for the bug report!

**Comment by karlb** [comment]
The problem should be resolved now, see https://www.wikdict.com/en-ja/car .

If the results are not like you expect or you see any similar problems, please report back!

**Comment by ookiiwi** [comment]
Seems good to me. I'haven't found any other missing entries for now but I'll surely report if so.
Thank you !!
