### ISSUE TITLE
Make the wdweb databases available for download?

### ISSUE THREAD

**Issue by vangberg** [karlb/wikdict-gen#17]
Hey

I want to create an autocompletion integration between CodeMirror and the wikdict-database, i.e. use autocomplete to translate words.

From your code it seems like the `translation_block` table in the `wdweb` database would be the easiest way to go from an English word to a German translation + its 'senses'.

Would it be possible to make that database available for download?

**Comment by karlb** [comment]
They already are available at https://download.wikdict.com/dictionaries/wdweb/. Be aware that the format of these files is considered an implementation detail and I will not try to keep it stable across different releases.

**Comment by vangberg** [comment]
Thanks! Here is the end result :)

https://github.com/vangberg/foreign-dispatch/tree/main/autocomplete

**Comment by karlb** [comment]
Cool, thanks for letting me know, @vangberg!
