### ISSUE TITLE
sdcv can't read some file(stardict format)

### ISSUE THREAD

**Issue by YTSummer23** [karlb/wikdict-gen#18]
I wanted to install dictionaries on kindle pw with koreader. I did it, but e-reader didn't find any word. Then I installed PC version koreader. It also didn't work. But I found out that this problem("nitems == 1 isn't true") occurs only with wikdict. I looked in a source code of sdcv.  And sdcv just can't read some file, fread returns 0. I tried to generate the files myself, but "make insert" just gets stuck after it creates "bg.inserted". I know nothing about docker, virtuoso and sql, so that's not a problem I can solve myself.

**Comment by karlb** [comment]
When I download and unzip https://download.wikdict.com/dictionaries/stardict/wikdict-en-de.zip, I can use sdcv just fine:
```
$ sdcv -x2 wikdict-en-de hand
save to cache wikdict-en-de/stardict.idx
Found 1 items, similar to hand.
-->English-Deutsch FreeDict+WikDict dictionary (en-de)
-->hand

<div>/<font color="gray">hænd</font>/<br>
<font color="green">noun</font><br><ol><li>handwriting; style of penmanship<ol><li><div>Handschrift</div></li><li><div>Schrift</div></li></ol></li><li>index or pointer on a dial, such as on an analogue/analog clock<div>Zeiger</div></li><li>part of the fore limb<div>Hand</div></li><li>servant, laborer, workman, trained for special duty; a performer<div>Handlanger</div></li><li>set of cards held by a player in a card game<ol><li><div>Hand</div></li><li><div>Blatt</div></li></ol></li><li>side; part; direction, either right or left<ol><li><div>Hand</div></li><li><div>Seite</div></li></ol></li><li>small part of a gunstock near the lock, grasped when aiming<div>Handgriff</div></li><li>that which is, or may be, held in a hand at once<div>Handvoll</div></li></ol></div>
```

Which dictionary and command are you using?

**Comment by YTSummer23** [comment]
Thanks for reply.
When I use exactly the same command, wikdict works fine. But when wikdict directory is in the standard place(/usr/share/stardict/dic/), sdcv doesn't find a word throwing this error("nitems==1 not true"). Even with -x2 and full path. Then, I guess, that's bug of sdcv. But it is still weird, because ebook-reader-dict(also based wiktionary, but monolingual) works well.
I tried en-ru and en-de. The results are the same.

**Comment by YTSummer23** [comment]
pc sdcv began to work regardless of a directory after manipulations with permissions. But kindle version still didn't. Then I just copied wikdict to kindle again and everything began to work. I don't really understand what happened.
**I don't know why, but you should use wikdict in a download directory before copying it anywhere.**

**Comment by YTSummer23** [comment]
pc sdcv began to work regardless of a directory after manipulations with permissions. But kindle version still didn't. Then I just copied wikdict to kindle again and everything began to work. I don't really understand what happened.
I don't know why, but **you should use wikdict in a download directory(with "-x2") before copying it anywhere.**
