### ISSUE TITLE
Docs on sql structure?

### ISSUE THREAD

**Issue by mockdeep** [karlb/wikdict-gen#19]
Hi there, thanks so much for providing these dictionaries!

I'm trying to build (yet another) flash card app, and I was hoping to make use of the sqlite dictionaries. One goal is to focus primarily on the most commonly used words in a language and I'm wondering if any of the data provided in the dictionary covers this. I see `score` and `importance`, but when I order by those they don't quite match what I would expect to see as the most commonly used words. Is there any documentation of what each of the fields and tables represent? I'm also interested in understanding what the other columns represent as well.

**Comment by karlb** [comment]
AFAIK, there is not information about how common a word in the Wiktionary data set. To sort words, I derive the `importance` measure indirectly by assuming that important words have more senses and translations than unimportant words. This is very useful to sort search results, but it has its limitations.

The `score` column for translations indicates the estimated quality of the translation, not the importance or frequency of the translated word.

If you are willing to merge different data sources (which I would advise against in most cases), have a look at https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists

I created some very basic Anki flash cards with the following script
```sh
echo "SELECT written_rep, replace(trans_list, ' | ', ', ') FROM simple_translation WHERE max_score >= 100 ORDER BY rel_importance DESC LIMIT 100;" \
 | sqlite3 dictionaries/generic/$1.sqlite3 -csv -noheader -separator ";" > $1.csv
```
but you probably already some something more advanced figured out.

**Comment by mockdeep** [comment]
@karlb thanks so much! That's very helpful. I'll poke around with those ideas.
