### ISSUE TITLE
Adding support for CAT<>EN and CAT<>ES

### ISSUE THREAD

**Issue by Andyvec** [karlb/wikdict-gen#22]
Hey,
I love the spirit of this project.
Would it be possible to add support from Catalan to English and Spanish, and the other way around?
Thanks in advance!

**Comment by karlb** [comment]
Now that dbnary supports Catalan, that should work. I'll try to include it in the next update.

**Comment by Andyvec** [comment]
Awesome!
Thank you so much

**Comment by karlb** [comment]
Could you please try out the Catalan dictionaries (only available on the web so far, no downloads)? I'm reliant on feedback for all the languages I don't speak myself.

**Comment by Andyvec** [comment]
Hey,
I have tested it a bit and It's working as expected. Thanks!
Looking forward to start using the StarDict version when it became available for downloading.

**Comment by karlb** [comment]
Good to hear! All downloads are there now. Let me know if something is off.

**Comment by Andyvec** [comment]
@karlb , I can't find the catalan StarDict files.
Am I looking in the right place?
https://download.wikdict.com/dictionaries/stardict/

**Comment by karlb** [comment]
That was an oversight on my part. It's there now.
