### ISSUE TITLE
Search live completion has trouble with Spanish word "ser" (verb "to be" in English)

### ISSUE THREAD

**Issue by hartwork** [karlb/wikdict-gen#9]
When switching to English-Spanish and the typing "ser" (verb "to be" in English) I see this:

![ser](https://user-images.githubusercontent.com/1577132/140994221-946d8e33-88a1-46ea-94ee-045d2caf077a.png)

What's interesting about that is that:
- Full match "ser" is not shown
- The list only shows English matches, while https://www.wikdict.com/en-es/ser is 100% Spanish matches.

Is that known and intended?

PS: Same with verb "ver" ("to see" in English)

**Comment by karlb** [comment]
Here's the upstream bug in dbnary: https://bitbucket.org/serasset/dbnary/issues/86/important-spanish-verbs-missing

**Comment by hartwork** [comment]
Thank you! :+1:

**Comment by hartwork** [comment]
Cool, thanks for the fix! :tada: :pray:
